dist: trusty
sudo: false
language: node_js

node_js:
  - '12'
cache:
  directories:
    - ./node_modules
install:
  - npm install -g @angular/cli
  - npm install -g nativescript
  - npm install
script:
  - npm build